#!/bin/bash
CMD=$1
if [ -z "$1" ]; then
  echo "Kali Docker: Command not found"
  exit 1
fi

#docker volume inspect kali-docker > /dev/null 2>&1
#if [ $? -eq 0 ]; then
#  echo "Mounting Docker volume: kali-docker"
#else
#  echo "Creating Docker volume: kali-docker"
#  docker volume create kali-docker > /dev/null 2>&1
#fi


docker build . -t devxops/kali-docker
CONTAINER_NAME="kali-$(date +%s | shasum | base64 | head -c 8 ; echo)"
DISPLAY=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}'):0
docker run --rm -it \
  -v "kali-docker:/opt" \
  -v "$(pwd)/kali-root:/root/:rw" \
  -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  -v "$HOME/.Xauthority:/root/.Xauthority" \
  --name $CONTAINER_NAME \
  -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` \
  -e DISPLAY=$DISPLAY \
  --net host \
  --hostname $CONTAINER_NAME \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  --privileged \
  --platform linux/arm64/v8 \
  devxops/kali-docker $CMD
